### ISSUE TITLE
Plugin replaces the multidex version by support library version

### ISSUE THREAD

**Issue by reytum** [NativeScript/push-plugin#149]
When running the project with the plugin added the build fails with following error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'demo'.
> Could not resolve all dependencies for configuration ':_F0F1F2DebugApkCopy'.
   > Could not find any version that matches com.android.support:multidex:26.0.+.
     Versions that do not match:
         1.0.1
         1.0.0
         1.0.2
     Searched in the following locations:
         file:/home/reytum/Android/Sdk/extras/android/m2repository/com/android/support/multidex/maven-metadata.xml
         file:/home/reytum/Projects/Applozic-latest/NativeScript/Latest/Applozic-NativeScript-Chat-Plugin/demo/platforms/android/sdk-manager/com/android/support/multid$
x/maven-metadata.xml
         file:/home/reytum/Projects/Applozic-latest/NativeScript/Latest/Applozic-NativeScript-Chat-Plugin/demo/platforms/android/sdk-manager/com/android/support/multid$
x/
After cloning the plugin and removing the multidex dependency from gradle and then adding the plugin to my project it works fine.

**Comment by leifermendez** [comment]
I have the same problem!

**Comment by lini** [comment]
Please update to the latest version of the plugin and the NativeScript runtime. This issue was reported for an older version of NativeScript and the push notifications plugin and should be fixed in the latest builds.

**Comment by j99ht** [comment]
I still have the same issue. I have installed version 1.1.3 of the plugin  and running Nativescript 3.4.3, tns-core-modules 3.4.1 and tns-android platform 3.4.2

**Comment by reytum** [comment]
@j99ht @leifermendez Are you using any gradle script to replace the support library versions?
That is causing the issue. You can fix it by using the below script:

```
configurations.all {
       resolutionStrategy.eachDependency { DependencyResolveDetails details ->
           def requested = details.requested
          if (requested.group == 'com.android.support' && requested.name != 'multidex') {
               details.useVersion '27.0.2'
           }
       }
   }
```

**Comment by j99ht** [comment]
I had to add this 
`if (requested.group == 'com.android.support' && requested.name != 'multidex' && requested.name != 'multidex-instrumentation')`

But now I'm getting this error 
`Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.8.0`

I have configured
```
compile 'com.google.firebase:firebase-messaging: 11.8.0' 
compile 'com.google.android.gms:play-services-location:11.8.0'

And still getting version conflict.
```

**Comment by reytum** [comment]
@j99ht This is not the support library version conflict, its google libraries conflict version, you can add a similar script below the above script for firebase and gms too:
```
configurations.all {
       resolutionStrategy.eachDependency { DependencyResolveDetails details ->
           def requested = details.requested
          if (requested.group == 'com.google.firebase' || requested.group == 'com.google.android.gms') {
               details.useVersion '11.8.0'
           }
       }
   }
```

**Comment by j99ht** [comment]
Fixed with
```
project.ext {
    firebaseMessagingVersion = "11.4.0" // OR the version you wish
}
```
in app.gradle
and removed all the other scripts. Thanks for your help

**Comment by nsplugins** [comment]
Closing the issue. Problem is solved.
